#!/bin/bash
#SBATCH --job-name=fpt-for-eeg
#SBATCH --time=24:00:00
#SBATCH --gpus=4
#SBATCH --cpus-per-gpu=4
#SBATCH -p pascal_gpu

module load PyTorch/1.7.1-fosscuda-2020b
module load torchvision/0.8.2-fosscuda-2020b-PyTorch-1.7.1
module load wandb/0.12.5-GCCcore-10.2.0

cd ~/fpt-for-eeg
export PYTHONPATH=$VSC_HOME/fpt-for-eeg:$PYTHONPATH
export WANDB_API_KEY=32c332a8b457162261635d4a8a940da285a355f0
export MNE_DATA=$VSC_DATA/mne_data

python scripts/run.py --cluster 
