#!/bin/bash
#SBATCH --job-name=fpt-for-eeg
#SBATCH --time=24:00:00
#PBS -l nodes=1:ppn=4:gpus=1:feature=kepler

module load PyTorch/1.7.1-fosscuda-2020b
module load torchvision/0.8.2-fosscuda-2020b-PyTorch-1.7.1
module load wandb/0.12.5-GCCcore-10.2.0

cd ~/fpt-for-eeg
export PYTHONPATH=~/fpt-for-eeg:$PYTHONPATH
export WANDB_API_KEY=32c332a8b457162261635d4a8a940da285a355f0

python scripts/run.py --cluster
