Configuratron:
  use_only:
    - bci_iv_2a
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False

encoder_weights: <saved encoder weights>
context_weights: <saved transformer weights>

datasets: !include configs/downstream_datasets.yml
