Configuratron:
  use_only:
    - bci_iv_2a
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False
  relative_directory: /user/brussel/102/vsc10248/fpt-for-eeg

encoder_weights: data/weights/encoder.pt
context_weights: data/weights/contextualizer.pt

datasets: !include configs/downstream_datasets.yml
