Configuratron:
  use_only:
    - graz_A
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False

encoder_weights: data/weights/encoder.pt
context_weights: data/weights/contextualizer.pt

datasets: !include configs/downstream_datasets.yml
