mmidb:
bci_iv_2a:
  name: "BCI Competition IV 2a"
  toplevel: data/competition/processed
  tmin: -2
  tlen: 6
  data_max: 100
  data_min: -100
  extensions:
    - .fif
  picks:
    - eeg
  train_params:
    epochs: 15
    batch_size: 60
    lr: 0.00005
    weight_decay: 0.05
    enc_do: 0.0
    feat_do: 0.0
    freeze_until: 6
